/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import javax.swing.JOptionPane;
import service.NumberGuessingService;
import service.OutOfRangeException;

/**
 *
 * @author dnoonan1
 */
public class NumberGuessingGame extends javax.swing.JFrame {

    private static final String EMPTY_STRING = "";
    private static final String MAIN_WINDOW_TITLE = "Guessing Game";
    private static final String ERROR_TITLE = "Error";
    private static final int LOWEST = NumberGuessingService.DEFAULT_MIN_VALUE;
    private static final int HIGHEST = NumberGuessingService.DEFAULT_MAX_VALUE;
    
    private NumberGuessingService guessingService;
    
    /**
     * Creates new form NumberGuessingGame
     */
    public NumberGuessingGame() {
        final String ENTER_LOWEST_MSG = "Enter the lowest value:";
        final String ENTER_HIGHEST_MSG = "Enter the highest value:";
        final String MUST_BE_GREATER_THAN_MSG = "Highest value must be greater than lowest! Enter again.";
        int minValue, maxValue;
        initComponents();
        setTitle(MAIN_WINDOW_TITLE);
        lblResultMsg.setText(EMPTY_STRING);
        minValue = getIntValue(ENTER_LOWEST_MSG, LOWEST);
        maxValue = minValue;
        boolean valid = false;
        while (!valid) {
            maxValue = getIntValue(ENTER_HIGHEST_MSG, HIGHEST);
            if (maxValue > minValue) {
                valid = true;
            } else {
                JOptionPane.showMessageDialog(null, MUST_BE_GREATER_THAN_MSG);
            }
        }
        guessingService = new NumberGuessingService(minValue, maxValue);
        lblRange.setText("Guess a number between " + minValue
                + " and " + maxValue + ".");
    }
    
    private int getIntValue(String msg, int defaultValue) {
        final String ERROR_MSG = "Please enter an integer.";
        int value = 0;
        boolean valid = false;
        while (!valid) {
            try {
                value = Integer.parseInt(JOptionPane.showInputDialog(null, msg, defaultValue));
                valid = true;
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, ERROR_MSG, ERROR_TITLE, JOptionPane.ERROR_MESSAGE);
            }
        }
        return value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInputGuess = new javax.swing.JTextField();
        btnGuess = new javax.swing.JButton();
        lblRange = new javax.swing.JLabel();
        lblInputGuess = new javax.swing.JLabel();
        lblResultMsg = new javax.swing.JLabel();
        btnNewNumber = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInputGuess.setText("0");
        txtInputGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputGuessActionPerformed(evt);
            }
        });

        btnGuess.setText("Guess");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        lblRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRange.setText("Guess a number between 1 and 100.");

        lblInputGuess.setText("Your guess:");

        lblResultMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultMsg.setText("You are correct!");

        btnNewNumber.setText("New Number");
        btnNewNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewNumber))
                    .addComponent(lblRange, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInputGuess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInputGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblResultMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRange, lblResultMsg});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnGuess, btnNewNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRange)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInputGuess))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuess)
                    .addComponent(btnNewNumber))
                .addGap(18, 18, 18)
                .addComponent(lblResultMsg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        
        final String WINDOW_TITLE = "Error";
        final String WRONG_FORMAT_MSG = "You must guess an integer value.";
        final String TOO_LOW_MSG = "Too low! Try again.";
        final String TOO_HIGH_MSG = "Too high! Try again.";
        final String CORRECT_MSG = "You are correct!";
        
        try {
            
            int guess = Integer.parseInt(txtInputGuess.getText());
            int difference = guessingService.checkGuess(guess);
        
            if (difference < 0) {
                lblResultMsg.setText(TOO_LOW_MSG);
            } else if (difference > 0) {
                lblResultMsg.setText(TOO_HIGH_MSG);
            } else { // difference == 0
                lblResultMsg.setText(CORRECT_MSG);
            }
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, WRONG_FORMAT_MSG, WINDOW_TITLE,
                    JOptionPane.ERROR_MESSAGE);
        } catch (OutOfRangeException ore) {
            JOptionPane.showMessageDialog(this,
                String.format("You must guess in the range %d to %d.",
                    guessingService.getMinValue(), guessingService.getMaxValue()
                ),
                WINDOW_TITLE, JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnGuessActionPerformed

    private void txtInputGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputGuessActionPerformed

    private void btnNewNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewNumberActionPerformed
        guessingService.newRandomNumber();
        lblResultMsg.setText(EMPTY_STRING);
    }//GEN-LAST:event_btnNewNumberActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnNewNumber;
    private javax.swing.JLabel lblInputGuess;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblResultMsg;
    private javax.swing.JTextField txtInputGuess;
    // End of variables declaration//GEN-END:variables
}
